// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonitorIMP.Infrastructure.Persistence;

#nullable disable

namespace MonitorIMP.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Agente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("int");

                    b.Property<string>("UltimaIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime?>("UltimoHeartBeat")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("UltimoHeartBeat");

                    b.HasIndex("Estado", "UltimoHeartBeat");

                    b.HasIndex("RestauranteId", "Codigo")
                        .IsUnique();

                    b.ToTable("Agentes", (string)null);
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.AgenteCredencial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRevocacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("HashSecreto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UltimoUso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId", "Activo");

                    b.ToTable("AgenteCredenciales", (string)null);
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AgenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosNuevos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("FranquiciaId")
                        .HasColumnType("int");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<int>("Origen")
                        .HasColumnType("int");

                    b.Property<int?>("RestauranteId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaEvento")
                        .IsDescending();

                    b.HasIndex("AgenteId", "FechaEvento")
                        .IsDescending(false, true)
                        .HasFilter("[AgenteId] IS NOT NULL");

                    b.HasIndex("FranquiciaId", "FechaEvento")
                        .IsDescending(false, true)
                        .HasFilter("[FranquiciaId] IS NOT NULL");

                    b.HasIndex("OrganizacionId", "FechaEvento")
                        .IsDescending(false, true)
                        .HasFilter("[OrganizacionId] IS NOT NULL");

                    b.HasIndex("Origen", "FechaEvento")
                        .IsDescending(false, true);

                    b.HasIndex("RestauranteId", "FechaEvento")
                        .IsDescending(false, true)
                        .HasFilter("[RestauranteId] IS NOT NULL");

                    b.HasIndex("UsuarioId", "FechaEvento")
                        .IsDescending(false, true)
                        .HasFilter("[UsuarioId] IS NOT NULL");

                    b.HasIndex("Entidad", "EntidadId", "FechaEvento")
                        .IsDescending(false, false, true);

                    b.ToTable("Auditorias", null, t =>
                        {
                            t.HasCheckConstraint("CK_Auditorias_OrigenActor", "(\r\n    (Origen = 1 AND UsuarioId IS NOT NULL AND AgenteId IS NULL)\r\n    OR\r\n    (Origen = 2 AND AgenteId IS NOT NULL AND UsuarioId IS NULL)\r\n    OR\r\n    (Origen IN (3, 4, 5) AND UsuarioId IS NULL AND AgenteId IS NULL)\r\n)");
                        });
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Franquicia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OrganizacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.HasIndex("OrganizacionId", "Codigo")
                        .IsUnique();

                    b.ToTable("Franquicias", (string)null);
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Impresora", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpActual")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Mac")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("int");

                    b.Property<string>("Serial")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("Estado");

                    b.HasIndex("Mac")
                        .IsUnique()
                        .HasFilter("[Mac] IS NOT NULL");

                    b.HasIndex("RestauranteId");

                    b.HasIndex("Serial")
                        .IsUnique()
                        .HasFilter("[Serial] IS NOT NULL");

                    b.HasIndex("RestauranteId", "Codigo")
                        .IsUnique();

                    b.ToTable("Impresoras", (string)null);
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.ImpresoraEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("ImpresoraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FechaEvento")
                        .IsDescending();

                    b.HasIndex("ImpresoraId", "EventoId")
                        .IsUnique();

                    b.HasIndex("ImpresoraId", "FechaEvento")
                        .IsDescending(false, true);

                    b.HasIndex("TipoEvento", "FechaEvento")
                        .IsDescending(false, true);

                    b.ToTable("ImpresoraEventos", (string)null);
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Organizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.HasIndex("Nombre");

                    b.ToTable("Organizaciones", (string)null);
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Restaurante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("FranquiciaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Ciudad");

                    b.HasIndex("Nombre");

                    b.HasIndex("FranquiciaId", "Codigo")
                        .IsUnique();

                    b.ToTable("Restaurantes", (string)null);
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Apellido");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Nombre");

                    b.HasIndex("Rol");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.UsuarioAcceso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FranquiciaId")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizacionId")
                        .HasColumnType("int");

                    b.Property<int?>("RestauranteId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FranquiciaId")
                        .HasFilter("[FranquiciaId] IS NOT NULL");

                    b.HasIndex("OrganizacionId")
                        .HasFilter("[OrganizacionId] IS NOT NULL");

                    b.HasIndex("RestauranteId")
                        .HasFilter("[RestauranteId] IS NOT NULL");

                    b.HasIndex("UsuarioId", "Activo");

                    b.HasIndex("UsuarioId", "FranquiciaId")
                        .IsUnique()
                        .HasFilter("[FranquiciaId] IS NOT NULL");

                    b.HasIndex("UsuarioId", "OrganizacionId")
                        .IsUnique()
                        .HasFilter("[OrganizacionId] IS NOT NULL");

                    b.HasIndex("UsuarioId", "RestauranteId")
                        .IsUnique()
                        .HasFilter("[RestauranteId] IS NOT NULL");

                    b.ToTable("UsuariosAccesos", null, t =>
                        {
                            t.HasCheckConstraint("CK_UsuariosAccesos_Nivel_Referencia", "(\r\n    (Nivel = 1 AND OrganizacionId IS NOT NULL AND FranquiciaId IS NULL AND RestauranteId IS NULL)\r\n    OR\r\n    (Nivel = 2 AND OrganizacionId IS NULL AND FranquiciaId IS NOT NULL AND RestauranteId IS NULL)\r\n    OR\r\n    (Nivel = 3 AND OrganizacionId IS NULL AND FranquiciaId IS NULL AND RestauranteId IS NOT NULL)\r\n)");
                        });
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Agente", b =>
                {
                    b.HasOne("MonitorIMP.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany("Agentes")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.AgenteCredencial", b =>
                {
                    b.HasOne("MonitorIMP.Domain.Entities.Agente", "Agente")
                        .WithMany("Credenciales")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agente");
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Auditoria", b =>
                {
                    b.HasOne("MonitorIMP.Domain.Entities.Agente", "Agente")
                        .WithMany("Auditorias")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MonitorIMP.Domain.Entities.Franquicia", "Franquicia")
                        .WithMany("Auditorias")
                        .HasForeignKey("FranquiciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MonitorIMP.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany("Auditorias")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MonitorIMP.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany("Auditorias")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MonitorIMP.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agente");

                    b.Navigation("Franquicia");

                    b.Navigation("Organizacion");

                    b.Navigation("Restaurante");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Franquicia", b =>
                {
                    b.HasOne("MonitorIMP.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany("Franquicias")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizacion");
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Impresora", b =>
                {
                    b.HasOne("MonitorIMP.Domain.Entities.Agente", "Agente")
                        .WithMany("Impresoras")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MonitorIMP.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany("Impresoras")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agente");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.ImpresoraEvento", b =>
                {
                    b.HasOne("MonitorIMP.Domain.Entities.Impresora", "Impresora")
                        .WithMany("Eventos")
                        .HasForeignKey("ImpresoraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Impresora");
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Restaurante", b =>
                {
                    b.HasOne("MonitorIMP.Domain.Entities.Franquicia", "Franquicia")
                        .WithMany("Restaurantes")
                        .HasForeignKey("FranquiciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Franquicia");
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.UsuarioAcceso", b =>
                {
                    b.HasOne("MonitorIMP.Domain.Entities.Franquicia", "Franquicia")
                        .WithMany("UsuarioAccesos")
                        .HasForeignKey("FranquiciaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MonitorIMP.Domain.Entities.Organizacion", "Organizacion")
                        .WithMany("UsuarioAccesos")
                        .HasForeignKey("OrganizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MonitorIMP.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany("UsuarioAccesos")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MonitorIMP.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioAccesos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Franquicia");

                    b.Navigation("Organizacion");

                    b.Navigation("Restaurante");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Agente", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Credenciales");

                    b.Navigation("Impresoras");
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Franquicia", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Restaurantes");

                    b.Navigation("UsuarioAccesos");
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Impresora", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Organizacion", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Franquicias");

                    b.Navigation("UsuarioAccesos");
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Restaurante", b =>
                {
                    b.Navigation("Agentes");

                    b.Navigation("Auditorias");

                    b.Navigation("Impresoras");

                    b.Navigation("UsuarioAccesos");
                });

            modelBuilder.Entity("MonitorIMP.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("UsuarioAccesos");
                });
#pragma warning restore 612, 618
        }
    }
}
